# renux remote repositories (GitHub Pages)
repository=https://renuxproject.github.io/renux-packages/current/bootstrap
repository=https://renuxproject.github.io/renux-packages/current
repository=https://renuxproject.github.io/renux-packages/current/debug
